site_name: DevOps Documentation
theme:
  name: material
  custom_dir: theme
extra:
  logo: "images/logo.png"
pages:
  - Introduction: index.md
  - Serverless FaaS:
    - AWS Serverless: aws-serverless.md
  - Chatbot:
    - Application Structure: structure.md
    - Release notes: release-notes.md
    - Samsung Chatbot: chatbot-samsung.md
  - BPM & ECM:
    - Installation: workforce-install.md
  - Blockchain:
    - Flight Delay: blockchain/flight-delay/index.md
    - Truffle Boilerplate: blockchain/flight-delay/index.md
markdown_extensions:
  - admonition
