site_name: DevOps Documentation
theme: 'material'
extra:
  logo: "images/logo.png"
theme_dir: 'theme'
pages:
  - Introduction: index.md
  - Release notes: release-notes.md
  - Developers:
    - Application Structure: structure.md
markdown_extensions:
  - admonition