site_name: DevOps Documentation
theme:
    name: material
    custom_dir: theme
extra:
  logo: "images/logo.png"
pages:
  - Introduction: index.md
  - Release notes: release-notes.md
  - Developers:
    - Application Structure: structure.md
markdown_extensions:
  - admonition