site_name: DevOps Documentation
theme:
    name: material
    custom_dir: theme
extra:
  logo: "images/logo.png"
pages:
  - Introduction: index.md
  - Serverless FaaS:
    - AWS Serverless: serverless_development.md
  - Chatbot:
    - Application Structure: structure.md
    - Release notes: release-notes.md
    - Samsung Chatbot: chatbot-samsung.md
  - BPM & ECM:
    - Installation: workforce-install.md  
  - Blockchain:
    - Blockchain Boilerplate: blockchain-boilerplate.md            
markdown_extensions:
  - admonition