site_name: DevOps Documentation
theme:
  name: material
  custom_dir: theme
extra:
  logo: "images/logo.png"
pages:
  - Introduction: docs/index.md
  - Serverless FaaS:
    - AWS Serverless: docs/aws-serverless.md
  - Chatbot:
    - Application Structure: docs/structure.md
    - Release notes: docs/release-notes.md
    - Samsung Chatbot: docs/chatbot-samsung.md
  - BPM & ECM:
    - Installation: docs/workforce-install.md
  - Blockchain:
    - Flight Delay: blockchain/flight-delay/index.md
    - Truffle Boilerplate: blockchain/flight-delay/index.md
markdown_extensions:
  - admonition
